DECLARE
   P_DD_COORDINATE    NUMBER;
   P_COORDINATE_TYPE  VARCHAR2(10);
   v_Return MEDSADMIN.GEOSPATIAL_UTIL.DMM_COORDINATE_TP;
BEGIN
   P_DD_COORDINATE    := -27.3408333333;
   P_COORDINATE_TYPE  := 'longitude';
   
   v_Return := GEOSPATIAL_UTIL.DD_TO_DMM(
      P_DD_COORDINATE   => P_DD_COORDINATE,
      P_COORDINATE_TYPE => P_COORDINATE_TYPE
   );

   DBMS_OUTPUT.PUT_LINE(v_Return.degrees);
   DBMS_OUTPUT.PUT_LINE(v_Return.decimal_minutes);
   DBMS_OUTPUT.PUT_LINE(v_Return.cardinal);
   
END;
