
update SEASOAR_TOW_OBSERVATION a
set a.location = MDSYS.sdo_geometry(2001, 4326, MDSYS.SDO_POINT_TYPE(a.LONGITUDE, a.LATITUDE, null), null, null);
/
commit;
/

DROP INDEX "MEDSADMIN"."SI_SEASOAR_TOW";

CREATE INDEX "MEDSADMIN"."SI_SEASOAR_TOW" ON "MEDSADMIN"."SEASOAR_TOW_OBSERVATION" ("LOCATION")  INDEXTYPE IS "MDSYS"."SPATIAL_INDEX_V2"  PARAMETERS (' ');
