

GRANT SELECT ON MEDSADMIN.CONNECTION_ID_GENERATOR TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I401 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I403 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I404 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I405 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I406 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I407 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I408 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I409 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I410 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I411 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I412 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I413 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I415 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I416 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I418 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I419 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I420 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I421 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I422 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I423 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I424 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I425 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I426 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I427 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I428 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I429 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I430 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I431 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I432 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I433 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I434 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I435 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I436 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I438 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I439 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I440 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I441 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I442 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I443 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I444 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I447 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I448 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I449 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I450 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I451 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I452 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I453 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I455 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I456 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I457 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I458 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I459 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I460 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I461 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I462 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I463 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I464 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I465 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I466 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I467 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I468 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I469 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I471 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I472 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I473 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I474 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I475 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I476 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I477 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I478 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I479 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I480 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I481 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I482 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I483 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I484 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I485 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I486 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I487 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I488 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I490 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I491 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I492 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I493 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I494 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I495 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I496 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I497 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I500 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I501 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I502 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I503 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I504 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I505 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I506 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I507 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I508 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I509 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I510 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I511 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I514 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I515 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.I520 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.LAYER_ID_GENERATOR TO PUBLIC;

GRANT SELECT ON MEDSADMIN.LAYER_SEQUENCE TO PUBLIC WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.LOCATOR_ID_GENERATOR TO PUBLIC;

GRANT SELECT ON MEDSADMIN.METADATA_ID_GENERATOR TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R100 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R101 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R104 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R105 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R107 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R108 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R111 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R112 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R113 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R114 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R115 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R116 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R117 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R118 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R123 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R124 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R125 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R126 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R127 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R128 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R129 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R13 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R130 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R131 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R133 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R135 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R137 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R138 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R139 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R141 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R144 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R146 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R147 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R148 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R149 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R152 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R157 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R161 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R162 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R163 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R164 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R167 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R168 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R169 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R170 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R171 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R172 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R173 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R174 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R175 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R176 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R177 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R178 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R179 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R18 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R180 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R181 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R182 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R184 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R186 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R187 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R188 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R189 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R19 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R190 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R191 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R192 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R193 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R194 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R197 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R199 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R2 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R20 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R201 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R202 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R22 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R222 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R223 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R224 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R225 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R230 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R232 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R233 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R234 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R236 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R238 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R24 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R241 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R245 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R246 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R247 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R248 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R250 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R251 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R253 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R255 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R257 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R258 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R26 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R261 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R262 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R263 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R264 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R265 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R266 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R267 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R268 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R269 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R270 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R271 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R272 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R273 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R274 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R275 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R276 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R277 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R278 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R279 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R283 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R285 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R286 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R287 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R288 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R289 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R290 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R293 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R294 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R295 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R296 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R298 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R3 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R300 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R301 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R303 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R305 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R307 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R308 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R309 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R310 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R311 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R312 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R313 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R314 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R315 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R316 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R317 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R318 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R319 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R320 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R321 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R322 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R323 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R325 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R326 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R327 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R328 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R329 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R330 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R331 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R334 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R335 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R336 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R337 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R338 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R339 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R340 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R342 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R343 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R344 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R345 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R346 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R347 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R348 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R349 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R350 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R351 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R352 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R353 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R354 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R355 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R356 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R358 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R359 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R360 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R361 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R362 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R363 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R364 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R365 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R366 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R367 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R368 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R369 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R370 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R371 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R372 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R373 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R374 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R375 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R377 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R378 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R379 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R380 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R381 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R382 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R383 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R384 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R387 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R388 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R389 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R390 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R391 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R392 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R393 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R394 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R395 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R396 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R397 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R398 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R401 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R402 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R405 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R407 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R409 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R414 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R416 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R417 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R419 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R420 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R421 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R432 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R5 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R6 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R7 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R79 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R80 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R92 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R93 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R94 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R95 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R97 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R98 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.R99 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.RASTERCOLUMN_ID_GENERATOR TO PUBLIC;

GRANT SELECT ON MEDSADMIN.SDE_BID_5 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.SDE_LOGFILE_LID_GEN TO PUBLIC;

GRANT SELECT ON MEDSADMIN.SDE_RID_5 TO PUBLIC;

GRANT SELECT ON MEDSADMIN.TABLE_ID_GENERATOR TO PUBLIC;

GRANT SELECT ON MEDSADMIN.VERSION_ID_GENERATOR TO PUBLIC;
