

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_SV TO AMOSS WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TONLY TO AMOSS WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TS TO AMOSS WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MEDSADMIN.TSSV_COUNT TO AMOSS;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_SV TO COCKRAMC WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TONLY TO COCKRAMC WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TS TO COCKRAMC WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MEDSADMIN.TSSV_COUNT TO COCKRAMC;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_SV TO GARIBBOS WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TONLY TO GARIBBOS WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TS TO GARIBBOS WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MEDSADMIN.TSSV_COUNT TO GARIBBOS;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_SV TO HUGHESA WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TONLY TO HUGHESA WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TS TO HUGHESA WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MEDSADMIN.TSSV_COUNT TO HUGHESA;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_SV TO LOCKS WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TONLY TO LOCKS WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TS TO LOCKS WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MEDSADMIN.TSSV_COUNT TO LOCKS;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_SV TO MEDSUSER WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TONLY TO MEDSUSER WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TS TO MEDSUSER WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_SV TO OPHERJ WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TONLY TO OPHERJ WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TS TO OPHERJ WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MEDSADMIN.TSSV_COUNT TO OPHERJ;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.ACCESS_CONTROL TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.DIRECTORY_LOOKUP TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.EXTRACTION_OPTION_LOOKUP TO PUBLIC WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.EXTRACTION_TYPES_LOOKUP TO PUBLIC WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.FILE_LOOKUP TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.FILE_PATH_LOOKUP TO PUBLIC WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.HELP TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.JOB_STATS TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.JOB_STATS_SETTINGS TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.JOB_TRACKING TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.LAYER_CRITERIA_LOOKUP TO PUBLIC WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.LAYER_LOOKUP TO PUBLIC WITH GRANT OPTION;

GRANT INSERT, SELECT, UPDATE ON MEDSADMIN.MAPINFO_MAPCATALOG TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.MEDS_ERRORS TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.MEDS_FLAGS TO PUBLIC WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.MEDS_FLAGS_ORIG TO PUBLIC WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.MEDS_JOB_ERROR TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.MEDS_JOB_TYPE TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.OBSERVATION TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.STANDARD_LOOKUP TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE ON MEDSADMIN.TIFF_CHARTS TO PUBLIC;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MEDSADMIN.TSSV_COUNT TO PUBLIC WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_SV TO WATKINSM WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TONLY TO WATKINSM WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TS TO WATKINSM WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MEDSADMIN.TSSV_COUNT TO WATKINSM;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_SV TO WHITEJ WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TONLY TO WHITEJ WITH GRANT OPTION;

GRANT SELECT ON MEDSADMIN.PROFILE_INDEX_TS TO WHITEJ WITH GRANT OPTION;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON MEDSADMIN.TSSV_COUNT TO WHITEJ;
