
ALTER TABLE MEDSADMIN.CRUISE_LAYER ADD (
  CONSTRAINT CRUISE_LAYER_IDX
  PRIMARY KEY
  (MEDS_CRUISE_NUMBER)
  USING INDEX MEDSADMIN.CRUISE_LAYER_IDX);

ALTER TABLE MEDSADMIN.GENERIC_EDIT ADD (
  UNIQUE (DATA_TYPE_ALIAS)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                NEXT             128K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE MEDSADMIN.HELP ADD (
  CONSTRAINT HELP_TOPIC_SEQ
  PRIMARY KEY
  (TOPIC, SEQ)
  USING INDEX MEDSADMIN.HELP_TOPIC_SEQ);

ALTER TABLE MEDSADMIN.INSTRUMENT ADD (
  CONSTRAINT INSTRUMENT_IDX
  PRIMARY KEY
  (SERD)
  USING INDEX MEDSADMIN.INSTRUMENT_IDX);

ALTER TABLE MEDSADMIN.JOB_TRACKING ADD (
  CONSTRAINT PK_JOB_TRACKING
  PRIMARY KEY
  (MEIC_NUMBER)
  USING INDEX MEDSADMIN.PK_JOB_TRACKING);

ALTER TABLE MEDSADMIN.MEDS_JOB_TYPE ADD (
  PRIMARY KEY
  (JOB_TYPE_NUMBER)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                NEXT             128K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

ALTER TABLE MEDSADMIN.MEDS_PROCESSING_JOB ADD (
  CONSTRAINT JOB_LAYER_IDX
  PRIMARY KEY
  (JOB_NUMBER)
  USING INDEX MEDSADMIN.JOB_LAYER_IDX);

ALTER TABLE MEDSADMIN.PROFILE_HEADER_SV ADD (
  CONSTRAINT PROFILE_HEADER_SV_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER)
  USING INDEX MEDSADMIN.PROFILE_HEADER_SV_IDX);

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TONLY ADD (
  CONSTRAINT PROFILE_HEADER_TONLY_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER)
  USING INDEX MEDSADMIN.PROFILE_HEADER_TONLY_IDX);

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TS ADD (
  CONSTRAINT PROFILE_HEADER_TS_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER)
  USING INDEX MEDSADMIN.PROFILE_HEADER_TS_IDX);

ALTER TABLE MEDSADMIN.PROFILE_INDEX_SV ADD (
  CONSTRAINT PROFILE_INDEX_SV_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER)
  USING INDEX MEDSADMIN.PROFILE_INDEX_SV_IDX);

ALTER TABLE MEDSADMIN.PROFILE_INDEX_TONLY ADD (
  CONSTRAINT PROFILE_INDEX_TONLY_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER)
  USING INDEX MEDSADMIN.PROFILE_INDEX_TONLY_IDX);

ALTER TABLE MEDSADMIN.PROFILE_INDEX_TS ADD (
  CONSTRAINT PROFILE_INDEX_TS_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER)
  USING INDEX MEDSADMIN.PROFILE_INDEX_TS_IDX);
