ALTER TABLE MEDSADMIN.ACCESS_CONTROL MODIFY 
  TABLE_NAME NULL;

ALTER TABLE MEDSADMIN.ACCESS_CONTROL MODIFY 
  USER_NAME NULL;

ALTER TABLE MEDSADMIN.ACCESS_CONTROL ADD (
  TABLE_NAME NOT NULL,
  USER_NAME NOT NULL);

ALTER TABLE MEDSADMIN."BIN$I1/4JeoZSqGQ/YxCEzRLPA==$0" MODIFY 
  FIELD_NAME NULL;

ALTER TABLE MEDSADMIN."BIN$I1/4JeoZSqGQ/YxCEzRLPA==$0" ADD (
  FIELD_NAME CONSTRAINT "BIN$QSyPObDkSKWkF0cztu843w==$0" NOT NULL);

ALTER TABLE MEDSADMIN."BIN$O0EUpaZQQZy/XSdW8tF2GQ==$0" MODIFY 
  ROW_TYPE NULL;

ALTER TABLE MEDSADMIN."BIN$O0EUpaZQQZy/XSdW8tF2GQ==$0" MODIFY 
  TABLE_NAME NULL;

ALTER TABLE MEDSADMIN."BIN$O0EUpaZQQZy/XSdW8tF2GQ==$0" ADD (
  ROW_TYPE CONSTRAINT "BIN$HFtB3cajSLSNFkVEz7xDGA==$0" NOT NULL,
  TABLE_NAME CONSTRAINT "BIN$OnZRJ7GSRdizC7WP7DGAjw==$0" NOT NULL);

ALTER TABLE MEDSADMIN.DIRECTORY_LOOKUP MODIFY 
  USER_NAME NULL;

ALTER TABLE MEDSADMIN.DIRECTORY_LOOKUP MODIFY 
  LOOKUP_TYPE NULL;

ALTER TABLE MEDSADMIN.DIRECTORY_LOOKUP MODIFY 
  FILE_PATH NULL;

ALTER TABLE MEDSADMIN.DIRECTORY_LOOKUP ADD (
  USER_NAME NOT NULL,
  LOOKUP_TYPE NOT NULL,
  FILE_PATH NOT NULL);

ALTER TABLE MEDSADMIN.EVENTLOG MODIFY 
  ID NULL;

ALTER TABLE MEDSADMIN.EVENTLOG ADD (
  ID NOT NULL);

ALTER TABLE MEDSADMIN.EVENTTYPE MODIFY 
  ID NULL;

ALTER TABLE MEDSADMIN.EVENTTYPE ADD (
  ID NOT NULL);

ALTER TABLE MEDSADMIN.FIELD_LOOKUP MODIFY 
  FIELD_NAME NULL;

ALTER TABLE MEDSADMIN.FIELD_LOOKUP ADD (
  FIELD_NAME NOT NULL);

ALTER TABLE MEDSADMIN.FILE_LOOKUP MODIFY 
  FILE_NAME NULL;

ALTER TABLE MEDSADMIN.FILE_LOOKUP MODIFY 
  PATH_NAME NULL;

ALTER TABLE MEDSADMIN.FILE_LOOKUP ADD (
  FILE_NAME NOT NULL,
  PATH_NAME NOT NULL);

ALTER TABLE MEDSADMIN.GENERIC_EDIT MODIFY 
  ROW_TYPE NULL;

ALTER TABLE MEDSADMIN.GENERIC_EDIT MODIFY 
  TABLE_NAME NULL;

ALTER TABLE MEDSADMIN.GENERIC_EDIT
  DROP CONSTRAINT SYS_C0011769;

ALTER TABLE MEDSADMIN.GENERIC_EDIT ADD (
  ROW_TYPE NOT NULL,
  TABLE_NAME NOT NULL,
  UNIQUE (DATA_TYPE_ALIAS));

ALTER TABLE MEDSADMIN.HELP MODIFY 
  TOPIC NULL;

ALTER TABLE MEDSADMIN.HELP MODIFY 
  SEQ NULL;

ALTER TABLE MEDSADMIN.HELP
  DROP CONSTRAINT HELP_TOPIC_SEQ;

ALTER TABLE MEDSADMIN.HELP ADD (
  TOPIC NOT NULL,
  SEQ NOT NULL,
  CONSTRAINT HELP_TOPIC_SEQ
  PRIMARY KEY
  (TOPIC, SEQ));

ALTER TABLE MEDSADMIN.INSTRUMENT MODIFY 
  SERD NULL;

ALTER TABLE MEDSADMIN.INSTRUMENT
  DROP CONSTRAINT INSTRUMENT_IDX;

ALTER TABLE MEDSADMIN.INSTRUMENT ADD (
  SERD NOT NULL,
  CONSTRAINT INSTRUMENT_IDX
  PRIMARY KEY
  (SERD));

ALTER TABLE MEDSADMIN.JOB_STATS MODIFY 
  DESCRIPTION NULL;

ALTER TABLE MEDSADMIN.JOB_STATS MODIFY 
  PERIOD_START NULL;

ALTER TABLE MEDSADMIN.JOB_STATS MODIFY 
  PERIOD_END NULL;

ALTER TABLE MEDSADMIN.JOB_STATS ADD (
  DESCRIPTION NOT NULL,
  PERIOD_START NOT NULL,
  PERIOD_END NOT NULL);

ALTER TABLE MEDSADMIN.JOB_STATS_SETTINGS MODIFY 
  VALUE NULL;

ALTER TABLE MEDSADMIN.JOB_STATS_SETTINGS MODIFY 
  DAY NULL;

ALTER TABLE MEDSADMIN.JOB_STATS_SETTINGS MODIFY 
  MONTH NULL;

ALTER TABLE MEDSADMIN.JOB_STATS_SETTINGS MODIFY 
  YEAR NULL;

ALTER TABLE MEDSADMIN.JOB_STATS_SETTINGS MODIFY 
  INTERVAL NULL;

ALTER TABLE MEDSADMIN.JOB_STATS_SETTINGS MODIFY 
  NUM_INTERVALS NULL;

ALTER TABLE MEDSADMIN.JOB_STATS_SETTINGS MODIFY 
  TOTAL NULL;

ALTER TABLE MEDSADMIN.JOB_STATS_SETTINGS ADD (
  VALUE NOT NULL,
  DAY NOT NULL,
  MONTH NOT NULL,
  YEAR NOT NULL,
  INTERVAL NOT NULL,
  NUM_INTERVALS NOT NULL,
  TOTAL NOT NULL);

ALTER TABLE MEDSADMIN.JOB_TRACKING MODIFY 
  STATUS NULL;

ALTER TABLE MEDSADMIN.JOB_TRACKING MODIFY 
  JOB_TYPE_NUMBER NULL;

ALTER TABLE MEDSADMIN.JOB_TRACKING MODIFY 
  ACKNOWLEDGE NULL;

ALTER TABLE MEDSADMIN.JOB_TRACKING MODIFY 
  PRIORITY_REGION1 NULL;

ALTER TABLE MEDSADMIN.JOB_TRACKING MODIFY 
  PRIORITY_REGION2 NULL;

ALTER TABLE MEDSADMIN.JOB_TRACKING MODIFY 
  PRIORITY_REGION3 NULL;

ALTER TABLE MEDSADMIN.JOB_TRACKING MODIFY 
  PRIORITY_REGION4 NULL;

ALTER TABLE MEDSADMIN.JOB_TRACKING MODIFY 
  PRIORITY_REGION5 NULL;

ALTER TABLE MEDSADMIN.JOB_TRACKING MODIFY 
  PRIORITY_REGION6 NULL;

ALTER TABLE MEDSADMIN.JOB_TRACKING
  DROP CONSTRAINT PK_JOB_TRACKING;

ALTER TABLE MEDSADMIN.JOB_TRACKING ADD (
  STATUS NOT NULL,
  JOB_TYPE_NUMBER NOT NULL,
  ACKNOWLEDGE NOT NULL,
  PRIORITY_REGION1 NOT NULL,
  PRIORITY_REGION2 NOT NULL,
  PRIORITY_REGION3 NOT NULL,
  PRIORITY_REGION4 NOT NULL,
  PRIORITY_REGION5 NOT NULL,
  PRIORITY_REGION6 NOT NULL,
  CONSTRAINT PK_JOB_TRACKING
  PRIMARY KEY
  (MEIC_NUMBER));

ALTER TABLE MEDSADMIN.LAYER_LOOKUP MODIFY 
  DATA_TABLE NULL;

ALTER TABLE MEDSADMIN.LAYER_LOOKUP ADD (
  DATA_TABLE NOT NULL);

ALTER TABLE MEDSADMIN.MEDS_ERRORS MODIFY 
  MEDS_ERROR_TYPE NULL;

ALTER TABLE MEDSADMIN.MEDS_ERRORS MODIFY 
  ERROR_DESCRIPTION NULL;

ALTER TABLE MEDSADMIN.MEDS_ERRORS ADD (
  MEDS_ERROR_TYPE NOT NULL,
  ERROR_DESCRIPTION NOT NULL);

ALTER TABLE MEDSADMIN.MEDS_JOB_ERROR MODIFY 
  MEIC_NUMBER NULL;

ALTER TABLE MEDSADMIN.MEDS_JOB_ERROR MODIFY 
  MEDS_ERROR_TYPE NULL;

ALTER TABLE MEDSADMIN.MEDS_JOB_ERROR MODIFY 
  NUM_ERRORS NULL;

ALTER TABLE MEDSADMIN.MEDS_JOB_ERROR ADD (
  MEIC_NUMBER NOT NULL,
  MEDS_ERROR_TYPE NOT NULL,
  NUM_ERRORS NOT NULL);

ALTER TABLE MEDSADMIN.MEDS_PROCESSING_JOB MODIFY 
  JOB_NUMBER NULL;

ALTER TABLE MEDSADMIN.MEDS_PROCESSING_JOB
  DROP CONSTRAINT JOB_LAYER_IDX;

ALTER TABLE MEDSADMIN.MEDS_PROCESSING_JOB ADD (
  JOB_NUMBER NOT NULL,
  CONSTRAINT JOB_LAYER_IDX
  PRIMARY KEY
  (JOB_NUMBER));

ALTER TABLE MEDSADMIN.MLO_COLUMNS MODIFY 
  TABLE_NAME NULL;

ALTER TABLE MEDSADMIN.MLO_COLUMNS MODIFY 
  COLUMN_NAME NULL;

ALTER TABLE MEDSADMIN.MLO_COLUMNS ADD (
  TABLE_NAME NOT NULL,
  COLUMN_NAME NOT NULL);

ALTER TABLE MEDSADMIN.OBSERVATION MODIFY 
  USER_NAME NULL;

ALTER TABLE MEDSADMIN.OBSERVATION MODIFY 
  JOB_NUMBER NULL;

ALTER TABLE MEDSADMIN.OBSERVATION MODIFY 
  OBSERVATION_NUMBER NULL;

ALTER TABLE MEDSADMIN.OBSERVATION ADD (
  USER_NAME NOT NULL,
  JOB_NUMBER NOT NULL,
  OBSERVATION_NUMBER NOT NULL);

ALTER TABLE MEDSADMIN.OBSERVATIONS MODIFY 
  MEDS_JOB_NUMBER NULL;

ALTER TABLE MEDSADMIN.OBSERVATIONS MODIFY 
  MEDS_OBSERVATION_NUMBER NULL;

ALTER TABLE MEDSADMIN.OBSERVATIONS ADD (
  MEDS_JOB_NUMBER NOT NULL,
  MEDS_OBSERVATION_NUMBER NOT NULL);

ALTER TABLE MEDSADMIN.PROFILE_HEADER_SV MODIFY 
  MEDS_OBSERVATION_NUMBER NULL;

ALTER TABLE MEDSADMIN.PROFILE_HEADER_SV MODIFY 
  MEDS_JOB_NUMBER NULL;

ALTER TABLE MEDSADMIN.PROFILE_HEADER_SV
  DROP CONSTRAINT PROFILE_HEADER_SV_IDX;

ALTER TABLE MEDSADMIN.PROFILE_HEADER_SV ADD (
  MEDS_OBSERVATION_NUMBER NOT NULL,
  MEDS_JOB_NUMBER NOT NULL,
  CONSTRAINT PROFILE_HEADER_SV_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER));

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TONLY MODIFY 
  MEDS_OBSERVATION_NUMBER NULL;

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TONLY MODIFY 
  MEDS_JOB_NUMBER NULL;

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TONLY
  DROP CONSTRAINT PROFILE_HEADER_TONLY_IDX;

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TONLY ADD (
  MEDS_OBSERVATION_NUMBER NOT NULL,
  MEDS_JOB_NUMBER NOT NULL,
  CONSTRAINT PROFILE_HEADER_TONLY_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER));

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TS MODIFY 
  MEDS_OBSERVATION_NUMBER NULL;

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TS MODIFY 
  MEDS_JOB_NUMBER NULL;

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TS
  DROP CONSTRAINT PROFILE_HEADER_TS_IDX;

ALTER TABLE MEDSADMIN.PROFILE_HEADER_TS ADD (
  MEDS_OBSERVATION_NUMBER NOT NULL,
  MEDS_JOB_NUMBER NOT NULL,
  CONSTRAINT PROFILE_HEADER_TS_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER));

ALTER TABLE MEDSADMIN.STATS_PERIOD MODIFY 
  PERIOD_START NULL;

ALTER TABLE MEDSADMIN.STATS_PERIOD MODIFY 
  PERIOD_END NULL;

ALTER TABLE MEDSADMIN.STATS_PERIOD ADD (
  PERIOD_START NOT NULL,
  PERIOD_END NOT NULL);

ALTER TABLE MEDSADMIN.TAB_COLUMNS MODIFY 
  TABLE_NAME NULL;

ALTER TABLE MEDSADMIN.TAB_COLUMNS MODIFY 
  COLUMN_NAME NULL;

ALTER TABLE MEDSADMIN.TAB_COLUMNS MODIFY 
  TAB_NUMBER NULL;

ALTER TABLE MEDSADMIN.TAB_COLUMNS ADD (
  TABLE_NAME NOT NULL,
  COLUMN_NAME NOT NULL,
  TAB_NUMBER NOT NULL);

ALTER TABLE MEDSADMIN.WVS_3M MODIFY 
  OBJECTID NULL;

ALTER TABLE MEDSADMIN.WVS_3M ADD (
  OBJECTID NOT NULL);

ALTER TABLE MEDSADMIN.WVS_3M_BATHY_LINE MODIFY 
  OBJECTID NULL;

ALTER TABLE MEDSADMIN.WVS_3M_BATHY_LINE ADD (
  OBJECTID NOT NULL);

ALTER TABLE MEDSADMIN.WVS_D_3M_COUNTPOLY MODIFY 
  OBJECTID NULL;

ALTER TABLE MEDSADMIN.WVS_D_3M_COUNTPOLY ADD (
  OBJECTID NOT NULL);

ALTER TABLE MEDSADMIN.CRUISE_LAYER
  DROP CONSTRAINT CRUISE_LAYER_IDX;

ALTER TABLE MEDSADMIN.CRUISE_LAYER ADD (
  CONSTRAINT CRUISE_LAYER_IDX
  PRIMARY KEY
  (MEDS_CRUISE_NUMBER));

ALTER TABLE MEDSADMIN.MEDS_JOB_TYPE
  DROP CONSTRAINT SYS_C0011767;

ALTER TABLE MEDSADMIN.MEDS_JOB_TYPE ADD (
  PRIMARY KEY
  (JOB_TYPE_NUMBER));

ALTER TABLE MEDSADMIN.PROFILE_INDEX_SV
  DROP CONSTRAINT PROFILE_INDEX_SV_IDX;

ALTER TABLE MEDSADMIN.PROFILE_INDEX_SV ADD (
  CONSTRAINT PROFILE_INDEX_SV_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER));

ALTER TABLE MEDSADMIN.PROFILE_INDEX_TONLY
  DROP CONSTRAINT PROFILE_INDEX_TONLY_IDX;

ALTER TABLE MEDSADMIN.PROFILE_INDEX_TONLY ADD (
  CONSTRAINT PROFILE_INDEX_TONLY_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER));

ALTER TABLE MEDSADMIN.PROFILE_INDEX_TS
  DROP CONSTRAINT PROFILE_INDEX_TS_IDX;

ALTER TABLE MEDSADMIN.PROFILE_INDEX_TS ADD (
  CONSTRAINT PROFILE_INDEX_TS_IDX
  PRIMARY KEY
  (MEDS_JOB_NUMBER, MEDS_OBSERVATION_NUMBER));
