

DROP PUBLIC SYNONYM WATER_COLOUR;

CREATE OR REPLACE PUBLIC SYNONYM WATER_COLOUR FOR MEDSADMIN.WATER_COLOUR;


DROP PUBLIC SYNONYM UNIFIED_WATER_COLOUR_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM UNIFIED_WATER_COLOUR_LOOKUP FOR MEDSADMIN.UNIFIED_WATER_COLOUR_LOOKUP;


DROP PUBLIC SYNONYM UNIFIED_SECCHI_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM UNIFIED_SECCHI_OBSERVATION FOR MEDSADMIN.UNIFIED_SECCHI_OBSERVATION;


DROP PUBLIC SYNONYM UNIFIED_SECCHI_DATA;

CREATE OR REPLACE PUBLIC SYNONYM UNIFIED_SECCHI_DATA FOR MEDSADMIN.UNIFIED_SECCHI_DATA;


DROP PUBLIC SYNONYM TSSV_COUNT;

CREATE OR REPLACE PUBLIC SYNONYM TSSV_COUNT FOR MEDSADMIN.TSSV_COUNT;


DROP PUBLIC SYNONYM TIFF_CHARTS;

CREATE OR REPLACE PUBLIC SYNONYM TIFF_CHARTS FOR MEDSADMIN.TIFF_CHARTS;


DROP PUBLIC SYNONYM TAB_COLUMNS;

CREATE OR REPLACE PUBLIC SYNONYM TAB_COLUMNS FOR MEDSADMIN.TAB_COLUMNS;


DROP PUBLIC SYNONYM TABLE_INDEX_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM TABLE_INDEX_LOOKUP FOR MEDSADMIN.TABLE_INDEX_LOOKUP;


DROP PUBLIC SYNONYM SUPPORT_TABLES;

CREATE OR REPLACE PUBLIC SYNONYM SUPPORT_TABLES FOR MEDSADMIN.SUPPORT_TABLES;


DROP PUBLIC SYNONYM STATS_PERIOD;

CREATE OR REPLACE PUBLIC SYNONYM STATS_PERIOD FOR MEDSADMIN.STATS_PERIOD;


DROP PUBLIC SYNONYM STANDARD_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM STANDARD_LOOKUP FOR MEDSADMIN.STANDARD_LOOKUP;


DROP PUBLIC SYNONYM SHIP_DETAILS;

CREATE OR REPLACE PUBLIC SYNONYM SHIP_DETAILS FOR MEDSADMIN.SHIP_DETAILS;


DROP PUBLIC SYNONYM SHIPPING_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM SHIPPING_OBSERVATION FOR MEDSADMIN.SHIPPING_OBSERVATION;


DROP PUBLIC SYNONYM SHIPPING_DATA;

CREATE OR REPLACE PUBLIC SYNONYM SHIPPING_DATA FOR MEDSADMIN.SHIPPING_DATA;


DROP PUBLIC SYNONYM SECCHI_WATER_COLOUR_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM SECCHI_WATER_COLOUR_LOOKUP FOR MEDSADMIN.SECCHI_WATER_COLOUR_LOOKUP;


DROP PUBLIC SYNONYM SECCHI_DISK_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM SECCHI_DISK_OBSERVATION FOR MEDSADMIN.SECCHI_DISK_OBSERVATION;


DROP PUBLIC SYNONYM SECCHI_DISK_DATA;

CREATE OR REPLACE PUBLIC SYNONYM SECCHI_DISK_DATA FOR MEDSADMIN.SECCHI_DISK_DATA;


DROP PUBLIC SYNONYM SEASOAR_TOW_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM SEASOAR_TOW_OBSERVATION FOR MEDSADMIN.SEASOAR_TOW_OBSERVATION;


DROP PUBLIC SYNONYM SEASOAR_TOW_DATA;

CREATE OR REPLACE PUBLIC SYNONYM SEASOAR_TOW_DATA FOR MEDSADMIN.SEASOAR_TOW_DATA;


DROP PUBLIC SYNONYM SEASOAR_PROFILE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM SEASOAR_PROFILE_OBSERVATION FOR MEDSADMIN.SEASOAR_PROFILE_OBSERVATION;


DROP PUBLIC SYNONYM SEASOAR_PROFILE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM SEASOAR_PROFILE_DATA FOR MEDSADMIN.SEASOAR_PROFILE_DATA;


DROP PUBLIC SYNONYM REPRES_SPECIES_L1;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_SPECIES_L1 FOR MEDSADMIN.REPRES_SPECIES_L1;


DROP PUBLIC SYNONYM REPRES_SHIPHITS_D1;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_SHIPHITS_D1 FOR MEDSADMIN.REPRES_SHIPHITS_D1;


DROP PUBLIC SYNONYM REPRES_SEASURFACE_L1;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_SEASURFACE_L1 FOR MEDSADMIN.REPRES_SEASURFACE_L1;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_SEP;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_SEP FOR MEDSADMIN.REPRES_PROFILE_L4_SEP;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_OCT;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_OCT FOR MEDSADMIN.REPRES_PROFILE_L4_OCT;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_NOV;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_NOV FOR MEDSADMIN.REPRES_PROFILE_L4_NOV;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_MAY;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_MAY FOR MEDSADMIN.REPRES_PROFILE_L4_MAY;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_MAR;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_MAR FOR MEDSADMIN.REPRES_PROFILE_L4_MAR;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_JUN;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_JUN FOR MEDSADMIN.REPRES_PROFILE_L4_JUN;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_JUL;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_JUL FOR MEDSADMIN.REPRES_PROFILE_L4_JUL;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_JAN;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_JAN FOR MEDSADMIN.REPRES_PROFILE_L4_JAN;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_FEB;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_FEB FOR MEDSADMIN.REPRES_PROFILE_L4_FEB;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_DEC;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_DEC FOR MEDSADMIN.REPRES_PROFILE_L4_DEC;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_AUG;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_AUG FOR MEDSADMIN.REPRES_PROFILE_L4_AUG;


DROP PUBLIC SYNONYM REPRES_PROFILE_L4_APR;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L4_APR FOR MEDSADMIN.REPRES_PROFILE_L4_APR;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_SEP;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_SEP FOR MEDSADMIN.REPRES_PROFILE_L2_SEP;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_OCT;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_OCT FOR MEDSADMIN.REPRES_PROFILE_L2_OCT;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_NOV;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_NOV FOR MEDSADMIN.REPRES_PROFILE_L2_NOV;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_MAY;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_MAY FOR MEDSADMIN.REPRES_PROFILE_L2_MAY;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_MAR;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_MAR FOR MEDSADMIN.REPRES_PROFILE_L2_MAR;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_JUN;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_JUN FOR MEDSADMIN.REPRES_PROFILE_L2_JUN;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_JUL;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_JUL FOR MEDSADMIN.REPRES_PROFILE_L2_JUL;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_JAN;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_JAN FOR MEDSADMIN.REPRES_PROFILE_L2_JAN;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_FEB;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_FEB FOR MEDSADMIN.REPRES_PROFILE_L2_FEB;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_DEC;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_DEC FOR MEDSADMIN.REPRES_PROFILE_L2_DEC;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_AUG;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_AUG FOR MEDSADMIN.REPRES_PROFILE_L2_AUG;


DROP PUBLIC SYNONYM REPRES_PROFILE_L2_APR;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L2_APR FOR MEDSADMIN.REPRES_PROFILE_L2_APR;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_SEP;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_SEP FOR MEDSADMIN.REPRES_PROFILE_L1_SEP;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_OCT;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_OCT FOR MEDSADMIN.REPRES_PROFILE_L1_OCT;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_NOV;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_NOV FOR MEDSADMIN.REPRES_PROFILE_L1_NOV;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_MAY;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_MAY FOR MEDSADMIN.REPRES_PROFILE_L1_MAY;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_MAR;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_MAR FOR MEDSADMIN.REPRES_PROFILE_L1_MAR;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_JUN;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_JUN FOR MEDSADMIN.REPRES_PROFILE_L1_JUN;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_JUL;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_JUL FOR MEDSADMIN.REPRES_PROFILE_L1_JUL;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_JAN;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_JAN FOR MEDSADMIN.REPRES_PROFILE_L1_JAN;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_FEB;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_FEB FOR MEDSADMIN.REPRES_PROFILE_L1_FEB;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_DEC;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_DEC FOR MEDSADMIN.REPRES_PROFILE_L1_DEC;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_AUG;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_AUG FOR MEDSADMIN.REPRES_PROFILE_L1_AUG;


DROP PUBLIC SYNONYM REPRES_PROFILE_L1_APR;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_PROFILE_L1_APR FOR MEDSADMIN.REPRES_PROFILE_L1_APR;


DROP PUBLIC SYNONYM REPRES_MIXEDLAYER_L2;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_MIXEDLAYER_L2 FOR MEDSADMIN.REPRES_MIXEDLAYER_L2;


DROP PUBLIC SYNONYM REPRES_MIXEDLAYER_L1;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_MIXEDLAYER_L1 FOR MEDSADMIN.REPRES_MIXEDLAYER_L1;


DROP PUBLIC SYNONYM REPRES_MIXEDLAYER_D1;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_MIXEDLAYER_D1 FOR MEDSADMIN.REPRES_MIXEDLAYER_D1;


DROP PUBLIC SYNONYM REPRES_IGPADS_L2;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_IGPADS_L2 FOR MEDSADMIN.REPRES_IGPADS_L2;


DROP PUBLIC SYNONYM REPRES_IGPADS_L1;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_IGPADS_L1 FOR MEDSADMIN.REPRES_IGPADS_L1;


DROP PUBLIC SYNONYM REPRES_AMBIENTNOISE_D1;

CREATE OR REPLACE PUBLIC SYNONYM REPRES_AMBIENTNOISE_D1 FOR MEDSADMIN.REPRES_AMBIENTNOISE_D1;


DROP PUBLIC SYNONYM REPEAT_TABLES_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM REPEAT_TABLES_LOOKUP FOR MEDSADMIN.REPEAT_TABLES_LOOKUP;


DROP PUBLIC SYNONYM PROFILE_WATER_COLOUR_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_WATER_COLOUR_LOOKUP FOR MEDSADMIN.PROFILE_WATER_COLOUR_LOOKUP;


DROP PUBLIC SYNONYM PROFILE_INDEX_TS;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_INDEX_TS FOR MEDSADMIN.PROFILE_INDEX_TS;


DROP PUBLIC SYNONYM PROFILE_INDEX_TONLY;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_INDEX_TONLY FOR MEDSADMIN.PROFILE_INDEX_TONLY;


DROP PUBLIC SYNONYM PROFILE_INDEX_SV;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_INDEX_SV FOR MEDSADMIN.PROFILE_INDEX_SV;


DROP PUBLIC SYNONYM PROFILE_HEADER_TS;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_HEADER_TS FOR MEDSADMIN.PROFILE_HEADER_TS;


DROP PUBLIC SYNONYM PROFILE_HEADER_TONLY;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_HEADER_TONLY FOR MEDSADMIN.PROFILE_HEADER_TONLY;


DROP PUBLIC SYNONYM PROFILE_HEADER_SV;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_HEADER_SV FOR MEDSADMIN.PROFILE_HEADER_SV;


DROP PUBLIC SYNONYM PROFILE_DATA_TS;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_DATA_TS FOR MEDSADMIN.PROFILE_DATA_TS;


DROP PUBLIC SYNONYM PROFILE_DATA_TONLY;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_DATA_TONLY FOR MEDSADMIN.PROFILE_DATA_TONLY;


DROP PUBLIC SYNONYM PROFILE_DATA_SV;

CREATE OR REPLACE PUBLIC SYNONYM PROFILE_DATA_SV FOR MEDSADMIN.PROFILE_DATA_SV;


DROP PUBLIC SYNONYM PRODUCTS_REGION_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM PRODUCTS_REGION_OBSERVATION FOR MEDSADMIN.PRODUCTS_REGION_OBSERVATION;


DROP PUBLIC SYNONYM PRODUCTS_REGION_DATA;

CREATE OR REPLACE PUBLIC SYNONYM PRODUCTS_REGION_DATA FOR MEDSADMIN.PRODUCTS_REGION_DATA;


DROP PUBLIC SYNONYM OMNI_AMBIENT_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM OMNI_AMBIENT_OBSERVATION FOR MEDSADMIN.OMNI_AMBIENT_OBSERVATION;


DROP PUBLIC SYNONYM OMNI_AMBIENT_DATA;

CREATE OR REPLACE PUBLIC SYNONYM OMNI_AMBIENT_DATA FOR MEDSADMIN.OMNI_AMBIENT_DATA;


DROP PUBLIC SYNONYM OCEAN_IMAGE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM OCEAN_IMAGE_OBSERVATION FOR MEDSADMIN.OCEAN_IMAGE_OBSERVATION;


DROP PUBLIC SYNONYM OCEAN_IMAGE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM OCEAN_IMAGE_DATA FOR MEDSADMIN.OCEAN_IMAGE_DATA;


DROP PUBLIC SYNONYM OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM OBSERVATION FOR MEDSADMIN.OBSERVATION;


DROP PUBLIC SYNONYM MONTH_LOOKUPS;

CREATE OR REPLACE PUBLIC SYNONYM MONTH_LOOKUPS FOR MEDSADMIN.MONTH_LOOKUPS;


DROP PUBLIC SYNONYM MLO_SOSUS_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_SOSUS_OBSERVATION FOR MEDSADMIN.MLO_SOSUS_OBSERVATION;


DROP PUBLIC SYNONYM MLO_SOSUS_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_SOSUS_DATA FOR MEDSADMIN.MLO_SOSUS_DATA;


DROP PUBLIC SYNONYM MLO_SHIP_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_SHIP_OBSERVATION FOR MEDSADMIN.MLO_SHIP_OBSERVATION;


DROP PUBLIC SYNONYM MLO_SHIP_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_SHIP_DATA FOR MEDSADMIN.MLO_SHIP_DATA;


DROP PUBLIC SYNONYM MLO_SEABED_CONTACT_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_SEABED_CONTACT_OBSERVATION FOR MEDSADMIN.MLO_SEABED_CONTACT_OBSERVATION;


DROP PUBLIC SYNONYM MLO_SEABED_CONTACT_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_SEABED_CONTACT_DATA FOR MEDSADMIN.MLO_SEABED_CONTACT_DATA;


DROP PUBLIC SYNONYM MLO_REPTILES_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_REPTILES_OBSERVATION FOR MEDSADMIN.MLO_REPTILES_OBSERVATION;


DROP PUBLIC SYNONYM MLO_REPTILES_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_REPTILES_DATA FOR MEDSADMIN.MLO_REPTILES_DATA;


DROP PUBLIC SYNONYM MLO_PINNIPEDS_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_PINNIPEDS_OBSERVATION FOR MEDSADMIN.MLO_PINNIPEDS_OBSERVATION;


DROP PUBLIC SYNONYM MLO_PINNIPEDS_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_PINNIPEDS_DATA FOR MEDSADMIN.MLO_PINNIPEDS_DATA;


DROP PUBLIC SYNONYM MLO_OTHERS_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_OTHERS_OBSERVATION FOR MEDSADMIN.MLO_OTHERS_OBSERVATION;


DROP PUBLIC SYNONYM MLO_OTHERS_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_OTHERS_DATA FOR MEDSADMIN.MLO_OTHERS_DATA;


DROP PUBLIC SYNONYM MLO_JELLYFISH_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_JELLYFISH_OBSERVATION FOR MEDSADMIN.MLO_JELLYFISH_OBSERVATION;


DROP PUBLIC SYNONYM MLO_JELLYFISH_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_JELLYFISH_DATA FOR MEDSADMIN.MLO_JELLYFISH_DATA;


DROP PUBLIC SYNONYM MLO_FISH_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_FISH_OBSERVATION FOR MEDSADMIN.MLO_FISH_OBSERVATION;


DROP PUBLIC SYNONYM MLO_FISH_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_FISH_DATA FOR MEDSADMIN.MLO_FISH_DATA;


DROP PUBLIC SYNONYM MLO_DATA_TYPE;

CREATE OR REPLACE PUBLIC SYNONYM MLO_DATA_TYPE FOR MEDSADMIN.MLO_DATA_TYPE;


DROP PUBLIC SYNONYM MLO_COLUMNS;

CREATE OR REPLACE PUBLIC SYNONYM MLO_COLUMNS FOR MEDSADMIN.MLO_COLUMNS;


DROP PUBLIC SYNONYM MLO_CETACEANS_TRACK;

CREATE OR REPLACE PUBLIC SYNONYM MLO_CETACEANS_TRACK FOR MEDSADMIN.MLO_CETACEANS_TRACK;


DROP PUBLIC SYNONYM MLO_CETACEANS_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_CETACEANS_OBSERVATION FOR MEDSADMIN.MLO_CETACEANS_OBSERVATION;


DROP PUBLIC SYNONYM MLO_CETACEANS_ENVELOPE;

CREATE OR REPLACE PUBLIC SYNONYM MLO_CETACEANS_ENVELOPE FOR MEDSADMIN.MLO_CETACEANS_ENVELOPE;


DROP PUBLIC SYNONYM MLO_CETACEANS_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_CETACEANS_DATA FOR MEDSADMIN.MLO_CETACEANS_DATA;


DROP PUBLIC SYNONYM MLO_BIRDS_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM MLO_BIRDS_OBSERVATION FOR MEDSADMIN.MLO_BIRDS_OBSERVATION;


DROP PUBLIC SYNONYM MLO_BIRDS_DATA;

CREATE OR REPLACE PUBLIC SYNONYM MLO_BIRDS_DATA FOR MEDSADMIN.MLO_BIRDS_DATA;


DROP PUBLIC SYNONYM MEDS_PROCESSING_JOB;

CREATE OR REPLACE PUBLIC SYNONYM MEDS_PROCESSING_JOB FOR MEDSADMIN.MEDS_PROCESSING_JOB;


DROP PUBLIC SYNONYM MEDS_JOB_TYPE;

CREATE OR REPLACE PUBLIC SYNONYM MEDS_JOB_TYPE FOR MEDSADMIN.MEDS_JOB_TYPE;


DROP PUBLIC SYNONYM MEDS_JOB_ERROR;

CREATE OR REPLACE PUBLIC SYNONYM MEDS_JOB_ERROR FOR MEDSADMIN.MEDS_JOB_ERROR;


DROP PUBLIC SYNONYM MEDS_IPR;

CREATE OR REPLACE PUBLIC SYNONYM MEDS_IPR FOR MEDSADMIN.MEDS_IPR;


DROP PUBLIC SYNONYM MEDS_FLAGS;

CREATE OR REPLACE PUBLIC SYNONYM MEDS_FLAGS FOR MEDSADMIN.MEDS_FLAGS;


DROP PUBLIC SYNONYM MEDS_ERRORS;

CREATE OR REPLACE PUBLIC SYNONYM MEDS_ERRORS FOR MEDSADMIN.MEDS_ERRORS;


DROP PUBLIC SYNONYM MASTER_GRID_L4;

CREATE OR REPLACE PUBLIC SYNONYM MASTER_GRID_L4 FOR MEDSADMIN.MASTER_GRID_L4;


DROP PUBLIC SYNONYM MASTER_GRID_L2;

CREATE OR REPLACE PUBLIC SYNONYM MASTER_GRID_L2 FOR MEDSADMIN.MASTER_GRID_L2;


DROP PUBLIC SYNONYM MASTER_GRID_L1;

CREATE OR REPLACE PUBLIC SYNONYM MASTER_GRID_L1 FOR MEDSADMIN.MASTER_GRID_L1;


DROP PUBLIC SYNONYM MASTER_GRID_D1;

CREATE OR REPLACE PUBLIC SYNONYM MASTER_GRID_D1 FOR MEDSADMIN.MASTER_GRID_D1;


DROP PUBLIC SYNONYM LEVEL_TABLES_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM LEVEL_TABLES_LOOKUP FOR MEDSADMIN.LEVEL_TABLES_LOOKUP;


DROP PUBLIC SYNONYM LAYER_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM LAYER_LOOKUP FOR MEDSADMIN.LAYER_LOOKUP;


DROP PUBLIC SYNONYM LAYER_CRITERIA_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM LAYER_CRITERIA_LOOKUP FOR MEDSADMIN.LAYER_CRITERIA_LOOKUP;


DROP PUBLIC SYNONYM JOB_TYPE;

CREATE OR REPLACE PUBLIC SYNONYM JOB_TYPE FOR MEDSADMIN.JOB_TYPE;


DROP PUBLIC SYNONYM JOB_TRACKING;

CREATE OR REPLACE PUBLIC SYNONYM JOB_TRACKING FOR MEDSADMIN.JOB_TRACKING;


DROP PUBLIC SYNONYM JOB_STATS_SETTINGS;

CREATE OR REPLACE PUBLIC SYNONYM JOB_STATS_SETTINGS FOR MEDSADMIN.JOB_STATS_SETTINGS;


DROP PUBLIC SYNONYM JOB_STATS;

CREATE OR REPLACE PUBLIC SYNONYM JOB_STATS FOR MEDSADMIN.JOB_STATS;


DROP PUBLIC SYNONYM JOB_LOOKUPS;

CREATE OR REPLACE PUBLIC SYNONYM JOB_LOOKUPS FOR MEDSADMIN.JOB_LOOKUPS;


DROP PUBLIC SYNONYM IW_WAVES;

CREATE OR REPLACE PUBLIC SYNONYM IW_WAVES FOR MEDSADMIN.IW_WAVES;


DROP PUBLIC SYNONYM IW_POINTS;

CREATE OR REPLACE PUBLIC SYNONYM IW_POINTS FOR MEDSADMIN.IW_POINTS;


DROP PUBLIC SYNONYM IW_PACKETS;

CREATE OR REPLACE PUBLIC SYNONYM IW_PACKETS FOR MEDSADMIN.IW_PACKETS;


DROP PUBLIC SYNONYM IW_IMAGE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM IW_IMAGE_OBSERVATION FOR MEDSADMIN.IW_IMAGE_OBSERVATION;


DROP PUBLIC SYNONYM IW_IMAGE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM IW_IMAGE_DATA FOR MEDSADMIN.IW_IMAGE_DATA;


DROP PUBLIC SYNONYM IPR_OWNER_TYPE;

CREATE OR REPLACE PUBLIC SYNONYM IPR_OWNER_TYPE FOR MEDSADMIN.IPR_OWNER_TYPE;


DROP PUBLIC SYNONYM IPR_OWNER_CONTACT;

CREATE OR REPLACE PUBLIC SYNONYM IPR_OWNER_CONTACT FOR MEDSADMIN.IPR_OWNER_CONTACT;


DROP PUBLIC SYNONYM IPR_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM IPR_LOOKUP FOR MEDSADMIN.IPR_LOOKUP;


DROP PUBLIC SYNONYM INTERNAL_WAVE_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM INTERNAL_WAVE_REPEAT FOR MEDSADMIN.INTERNAL_WAVE_REPEAT;


DROP PUBLIC SYNONYM INTERNAL_WAVE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM INTERNAL_WAVE_OBSERVATION FOR MEDSADMIN.INTERNAL_WAVE_OBSERVATION;


DROP PUBLIC SYNONYM INTERNAL_WAVE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM INTERNAL_WAVE_DATA FOR MEDSADMIN.INTERNAL_WAVE_DATA;


DROP PUBLIC SYNONYM INSTRUMENT;

CREATE OR REPLACE PUBLIC SYNONYM INSTRUMENT FOR MEDSADMIN.INSTRUMENT;


DROP PUBLIC SYNONYM GLIDER_THREADED_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM GLIDER_THREADED_OBSERVATION FOR MEDSADMIN.GLIDER_THREADED_OBSERVATION;


DROP PUBLIC SYNONYM GLIDER_THREADED_DATA;

CREATE OR REPLACE PUBLIC SYNONYM GLIDER_THREADED_DATA FOR MEDSADMIN.GLIDER_THREADED_DATA;


DROP PUBLIC SYNONYM GEOLOGY_QUALITY_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM GEOLOGY_QUALITY_OBSERVATION FOR MEDSADMIN.GEOLOGY_QUALITY_OBSERVATION;


DROP PUBLIC SYNONYM GEOLOGY_QUALITY_DATA;

CREATE OR REPLACE PUBLIC SYNONYM GEOLOGY_QUALITY_DATA FOR MEDSADMIN.GEOLOGY_QUALITY_DATA;


DROP PUBLIC SYNONYM GEOLOGY_PARAM_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM GEOLOGY_PARAM_OBSERVATION FOR MEDSADMIN.GEOLOGY_PARAM_OBSERVATION;


DROP PUBLIC SYNONYM GEOLOGY_PARAM_DATA;

CREATE OR REPLACE PUBLIC SYNONYM GEOLOGY_PARAM_DATA FOR MEDSADMIN.GEOLOGY_PARAM_DATA;


DROP PUBLIC SYNONYM GENERIC_EDIT;

CREATE OR REPLACE PUBLIC SYNONYM GENERIC_EDIT FOR MEDSADMIN.GENERIC_EDIT;


DROP PUBLIC SYNONYM FRONT_TRANSECT_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_TRANSECT_REPEAT FOR MEDSADMIN.FRONT_TRANSECT_REPEAT;


DROP PUBLIC SYNONYM FRONT_TRANSECT_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_TRANSECT_OBSERVATION FOR MEDSADMIN.FRONT_TRANSECT_OBSERVATION;


DROP PUBLIC SYNONYM FRONT_SURVEY_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_SURVEY_OBSERVATION FOR MEDSADMIN.FRONT_SURVEY_OBSERVATION;


DROP PUBLIC SYNONYM FRONT_SURVEY_DATA;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_SURVEY_DATA FOR MEDSADMIN.FRONT_SURVEY_DATA;


DROP PUBLIC SYNONYM FRONT_SATELLITE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_SATELLITE_OBSERVATION FOR MEDSADMIN.FRONT_SATELLITE_OBSERVATION;


DROP PUBLIC SYNONYM FRONT_MEAN_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_MEAN_REPEAT FOR MEDSADMIN.FRONT_MEAN_REPEAT;


DROP PUBLIC SYNONYM FRONT_MEAN_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_MEAN_OBSERVATION FOR MEDSADMIN.FRONT_MEAN_OBSERVATION;


DROP PUBLIC SYNONYM FRONT_MEAN_DATA;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_MEAN_DATA FOR MEDSADMIN.FRONT_MEAN_DATA;


DROP PUBLIC SYNONYM FRONT_IMAGE_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_IMAGE_REPEAT FOR MEDSADMIN.FRONT_IMAGE_REPEAT;


DROP PUBLIC SYNONYM FRONT_IMAGE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_IMAGE_DATA FOR MEDSADMIN.FRONT_IMAGE_DATA;


DROP PUBLIC SYNONYM FRONT_GRID_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_GRID_REPEAT FOR MEDSADMIN.FRONT_GRID_REPEAT;


DROP PUBLIC SYNONYM FRONT_GRID_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_GRID_OBSERVATION FOR MEDSADMIN.FRONT_GRID_OBSERVATION;


DROP PUBLIC SYNONYM FRONT_GRID_DATA;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_GRID_DATA FOR MEDSADMIN.FRONT_GRID_DATA;


DROP PUBLIC SYNONYM FRONT_FWOC_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_FWOC_REPEAT FOR MEDSADMIN.FRONT_FWOC_REPEAT;


DROP PUBLIC SYNONYM FRONT_FWOC_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_FWOC_OBSERVATION FOR MEDSADMIN.FRONT_FWOC_OBSERVATION;


DROP PUBLIC SYNONYM FRONT_DEPTH_PLAN_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_DEPTH_PLAN_REPEAT FOR MEDSADMIN.FRONT_DEPTH_PLAN_REPEAT;


DROP PUBLIC SYNONYM FRONT_DEPTH_PLAN_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM FRONT_DEPTH_PLAN_OBSERVATION FOR MEDSADMIN.FRONT_DEPTH_PLAN_OBSERVATION;


DROP PUBLIC SYNONYM FLAG_TYPES_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM FLAG_TYPES_LOOKUP FOR MEDSADMIN.FLAG_TYPES_LOOKUP;


DROP PUBLIC SYNONYM FILE_PATH_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM FILE_PATH_LOOKUP FOR MEDSADMIN.FILE_PATH_LOOKUP;


DROP PUBLIC SYNONYM FILE_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM FILE_LOOKUP FOR MEDSADMIN.FILE_LOOKUP;


DROP PUBLIC SYNONYM FIELD_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM FIELD_LOOKUP FOR MEDSADMIN.FIELD_LOOKUP;


DROP PUBLIC SYNONYM EXTRACTION_TYPES_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM EXTRACTION_TYPES_LOOKUP FOR MEDSADMIN.EXTRACTION_TYPES_LOOKUP;


DROP PUBLIC SYNONYM EXTRACTION_OPTION_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM EXTRACTION_OPTION_LOOKUP FOR MEDSADMIN.EXTRACTION_OPTION_LOOKUP;


DROP PUBLIC SYNONYM EDDY_SATELLITE_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM EDDY_SATELLITE_REPEAT FOR MEDSADMIN.EDDY_SATELLITE_REPEAT;


DROP PUBLIC SYNONYM EDDY_SATELLITE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM EDDY_SATELLITE_OBSERVATION FOR MEDSADMIN.EDDY_SATELLITE_OBSERVATION;


DROP PUBLIC SYNONYM EDDY_SATELLITE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM EDDY_SATELLITE_DATA FOR MEDSADMIN.EDDY_SATELLITE_DATA;


DROP PUBLIC SYNONYM EDDY_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM EDDY_REPEAT FOR MEDSADMIN.EDDY_REPEAT;


DROP PUBLIC SYNONYM EDDY_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM EDDY_OBSERVATION FOR MEDSADMIN.EDDY_OBSERVATION;


DROP PUBLIC SYNONYM EDDY_DATA;

CREATE OR REPLACE PUBLIC SYNONYM EDDY_DATA FOR MEDSADMIN.EDDY_DATA;


DROP PUBLIC SYNONYM DIVE_SITE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM DIVE_SITE_OBSERVATION FOR MEDSADMIN.DIVE_SITE_OBSERVATION;


DROP PUBLIC SYNONYM DIVE_SITE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM DIVE_SITE_DATA FOR MEDSADMIN.DIVE_SITE_DATA;


DROP PUBLIC SYNONYM DIR_AMBIENT_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM DIR_AMBIENT_REPEAT FOR MEDSADMIN.DIR_AMBIENT_REPEAT;


DROP PUBLIC SYNONYM DIR_AMBIENT_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM DIR_AMBIENT_OBSERVATION FOR MEDSADMIN.DIR_AMBIENT_OBSERVATION;


DROP PUBLIC SYNONYM DIR_AMBIENT_DATA;

CREATE OR REPLACE PUBLIC SYNONYM DIR_AMBIENT_DATA FOR MEDSADMIN.DIR_AMBIENT_DATA;


DROP PUBLIC SYNONYM DIRECTORY_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM DIRECTORY_LOOKUP FOR MEDSADMIN.DIRECTORY_LOOKUP;


DROP PUBLIC SYNONYM DEEP_SCATTERING_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM DEEP_SCATTERING_OBSERVATION FOR MEDSADMIN.DEEP_SCATTERING_OBSERVATION;


DROP PUBLIC SYNONYM DEEP_SCATTERING_DATA;

CREATE OR REPLACE PUBLIC SYNONYM DEEP_SCATTERING_DATA FOR MEDSADMIN.DEEP_SCATTERING_DATA;


DROP PUBLIC SYNONYM DBFIELD_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM DBFIELD_LOOKUP FOR MEDSADMIN.DBFIELD_LOOKUP;


DROP PUBLIC SYNONYM DATA_TYPES_TABLE;

CREATE OR REPLACE PUBLIC SYNONYM DATA_TYPES_TABLE FOR MEDSADMIN.DATA_TYPES_TABLE;


DROP PUBLIC SYNONYM DATASET_LOOKUP;

CREATE OR REPLACE PUBLIC SYNONYM DATASET_LOOKUP FOR MEDSADMIN.DATASET_LOOKUP;


DROP PUBLIC SYNONYM CRUISE_LAYER;

CREATE OR REPLACE PUBLIC SYNONYM CRUISE_LAYER FOR MEDSADMIN.CRUISE_LAYER;


DROP PUBLIC SYNONYM CLASS_INFORMATION;

CREATE OR REPLACE PUBLIC SYNONYM CLASS_INFORMATION FOR MEDSADMIN.CLASS_INFORMATION;


DROP PUBLIC SYNONYM CHART_PANEL;

CREATE OR REPLACE PUBLIC SYNONYM CHART_PANEL FOR MEDSADMIN.CHART_PANEL;


DROP PUBLIC SYNONYM BIOMASS_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM BIOMASS_OBSERVATION FOR MEDSADMIN.BIOMASS_OBSERVATION;


DROP PUBLIC SYNONYM BIOMASS_DATA;

CREATE OR REPLACE PUBLIC SYNONYM BIOMASS_DATA FOR MEDSADMIN.BIOMASS_DATA;


DROP PUBLIC SYNONYM BIOLUMINESCENCE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM BIOLUMINESCENCE_OBSERVATION FOR MEDSADMIN.BIOLUMINESCENCE_OBSERVATION;


DROP PUBLIC SYNONYM BIOLUMINESCENCE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM BIOLUMINESCENCE_DATA FOR MEDSADMIN.BIOLUMINESCENCE_DATA;


DROP PUBLIC SYNONYM BEACH_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM BEACH_OBSERVATION FOR MEDSADMIN.BEACH_OBSERVATION;


DROP PUBLIC SYNONYM BEACH_DATA;

CREATE OR REPLACE PUBLIC SYNONYM BEACH_DATA FOR MEDSADMIN.BEACH_DATA;


DROP PUBLIC SYNONYM ASRAP_POLYGON_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM ASRAP_POLYGON_REPEAT FOR MEDSADMIN.ASRAP_POLYGON_REPEAT;


DROP PUBLIC SYNONYM ASRAP_POLYGON_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM ASRAP_POLYGON_OBSERVATION FOR MEDSADMIN.ASRAP_POLYGON_OBSERVATION;


DROP PUBLIC SYNONYM ASRAP_POINT_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM ASRAP_POINT_REPEAT FOR MEDSADMIN.ASRAP_POINT_REPEAT;


DROP PUBLIC SYNONYM ASRAP_POINT_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM ASRAP_POINT_OBSERVATION FOR MEDSADMIN.ASRAP_POINT_OBSERVATION;


DROP PUBLIC SYNONYM ASRAP_POINT_DATA;

CREATE OR REPLACE PUBLIC SYNONYM ASRAP_POINT_DATA FOR MEDSADMIN.ASRAP_POINT_DATA;


DROP PUBLIC SYNONYM ASRAP_POINT_CADS_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM ASRAP_POINT_CADS_REPEAT FOR MEDSADMIN.ASRAP_POINT_CADS_REPEAT;


DROP PUBLIC SYNONYM AQUAPACK_PROFILE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM AQUAPACK_PROFILE_OBSERVATION FOR MEDSADMIN.AQUAPACK_PROFILE_OBSERVATION;


DROP PUBLIC SYNONYM AQUAPACK_PROFILE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM AQUAPACK_PROFILE_DATA FOR MEDSADMIN.AQUAPACK_PROFILE_DATA;


DROP PUBLIC SYNONYM AQUAPACK_LINE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM AQUAPACK_LINE_OBSERVATION FOR MEDSADMIN.AQUAPACK_LINE_OBSERVATION;


DROP PUBLIC SYNONYM AQUAPACK_LINE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM AQUAPACK_LINE_DATA FOR MEDSADMIN.AQUAPACK_LINE_DATA;


DROP PUBLIC SYNONYM AQUAPACK_JOB;

CREATE OR REPLACE PUBLIC SYNONYM AQUAPACK_JOB FOR MEDSADMIN.AQUAPACK_JOB;


DROP PUBLIC SYNONYM AQUA2081_LINE_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM AQUA2081_LINE_OBSERVATION FOR MEDSADMIN.AQUA2081_LINE_OBSERVATION;


DROP PUBLIC SYNONYM AQUA2081_LINE_DATA;

CREATE OR REPLACE PUBLIC SYNONYM AQUA2081_LINE_DATA FOR MEDSADMIN.AQUA2081_LINE_DATA;


DROP PUBLIC SYNONYM ADCP_REPEAT;

CREATE OR REPLACE PUBLIC SYNONYM ADCP_REPEAT FOR MEDSADMIN.ADCP_REPEAT;


DROP PUBLIC SYNONYM ADCP_OBSERVATION;

CREATE OR REPLACE PUBLIC SYNONYM ADCP_OBSERVATION FOR MEDSADMIN.ADCP_OBSERVATION;


DROP PUBLIC SYNONYM ADCP_DATA;

CREATE OR REPLACE PUBLIC SYNONYM ADCP_DATA FOR MEDSADMIN.ADCP_DATA;


DROP PUBLIC SYNONYM ACCESS_CONTROL;

CREATE OR REPLACE PUBLIC SYNONYM ACCESS_CONTROL FOR MEDSADMIN.ACCESS_CONTROL;


----

DROP PUBLIC SYNONYM JOB_TRACKING_VIEW;

CREATE OR REPLACE PUBLIC SYNONYM JOB_TRACKING_VIEW FOR MEDSADMIN.JOB_TRACKING_VIEW;

----

DROP PUBLIC SYNONYM MEIC_NUMBER_SEQUENCE;

CREATE OR REPLACE PUBLIC SYNONYM MEIC_NUMBER_SEQUENCE FOR MEDSADMIN.MEIC_NUMBER_SEQUENCE;


DROP PUBLIC SYNONYM LAYER_SEQUENCE;

CREATE OR REPLACE PUBLIC SYNONYM LAYER_SEQUENCE FOR MEDSADMIN.LAYER_SEQUENCE;

