DROP TABLE MAPINFO.MAPINFO_MAPCATALOG CASCADE CONSTRAINTS;

CREATE TABLE MAPINFO.MAPINFO_MAPCATALOG
(
  SPATIALTYPE       FLOAT(126),
  TABLENAME         VARCHAR2(32 BYTE),
  OWNERNAME         VARCHAR2(32 BYTE),
  SPATIALCOLUMN     VARCHAR2(32 BYTE),
  DB_X_LL           FLOAT(126),
  DB_Y_LL           FLOAT(126),
  DB_X_UR           FLOAT(126),
  DB_Y_UR           FLOAT(126),
  COORDINATESYSTEM  VARCHAR2(254 BYTE),
  SYMBOL            VARCHAR2(254 BYTE),
  XCOLUMNNAME       VARCHAR2(32 BYTE),
  YCOLUMNNAME       VARCHAR2(32 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MAPINFO.MAPCAT_I1 ON MAPINFO.MAPINFO_MAPCATALOG
(OWNERNAME, TABLENAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


GRANT INSERT, SELECT, UPDATE ON MAPINFO.MAPINFO_MAPCATALOG TO PUBLIC;
