DECLARE
   P_DD_COORDINATE    NUMBER;
   P_COORDINATE_TYPE  VARCHAR2(10);
   v_Return MEDSADMIN.GEOSPATIAL_UTIL.DMS_COORDINATE_TP;
BEGIN
   P_DD_COORDINATE    := 14.1693333333;
   P_COORDINATE_TYPE  := 'latitude';
   
   v_Return := GEOSPATIAL_UTIL.DD_TO_DMS(
      P_DD_COORDINATE   => P_DD_COORDINATE,
      P_COORDINATE_TYPE => P_COORDINATE_TYPE
   );

   DBMS_OUTPUT.PUT_LINE(v_Return.degrees);
   DBMS_OUTPUT.PUT_LINE(v_Return.minutes);
   DBMS_OUTPUT.PUT_LINE(v_Return.seconds);
   DBMS_OUTPUT.PUT_LINE(v_Return.cardinal);
   
END;
